### ISSUE TITLE
Install instructions: jupyter_nbextensions_configurator missing

### ISSUE THREAD

**Issue by Tobias-Fischer** [RoboStack/jupyterlab-ros#1]
I got this error on OSX when first trying to run jupyterlab: `[W 07:47:37.110 LabApp] Error loading server extension jupyter_nbextensions_configurator`. Easy workaround: `mamba install -c conda-forge jupyter_nbextensions_configurator`. Would be great if you could add this to the README.

**Comment by hbcarlos** [comment]
Hi Tobias, sorry for the late answer.
Can you give me more information? I can't reproduce the error.
Anyway, this extension is not registering a notebook extension, soo I'm not sure where this error comes from.
