### ISSUE TITLE
Examples fail when starting robot_state_publisher

### ISSUE THREAD

**Issue by romesco** [RoboStack/jupyterlab-ros#5]
Very cool idea! I wanted to try it out, but am struggling to get everything running properly within a self-contained conda env.

I followed the instructions on installation using conda/mamba, but I think there might be a dependency issue with the ros-melodic-<*> coming from the conda channels. I tried this on my local machine as well as on the binder setup in this repo.

When running either the joint_state_demo or the teleop_demo, I get this error:
```
/srv/conda/envs/notebook/lib/robot_state_publisher/robot_state_publisher: error while loading shared libraries: libPocoFoundation.so.60: cannot open shared object file: No such file or directory
```

To reproduce, just run the binder example, and use `!roslaunch turtlebot3_fake turtlebot3_fake.launch`.

I'm not sure if this link will work, but here is the binder I was running last:
https://mybinder.org/v2/gh/RoboStack/jupyterlab-ros/98c0a969255648181e62b229a39f8f12fb86edb1?filepath=examples%2FTurtlebot_teleop.ipynb

**Comment by hbcarlos** [comment]
Hi, I just tried locally and is not working seems like the library `libPocoFoundation.so.60` is missing. We need to build the package again.

Meanwhile, if you want to try you can make a symbolic link from the existing library and it works, In my case, I made a link from `libPocoFoundation.so.71` to `libPocoFoundation.so.60` and is working.

`ln -s "$CONDA_PREFIX/lib/libPocoFoundation.so.71" "$CONDA_PREFIX/lib/libPocoFoundation.so.60" `

**Comment by wolfv** [comment]
Thanks for the investigation Carlos! Looks like the wrong version of libpoco gets installed. We need to fix that. Libpoco should have a run exports to prevent this issue actually. One other way to fix this would be to install the older version of poco

**Comment by hbcarlos** [comment]
Maybe we can change the import to reference to `libPocoFoundation.so` and we don't have more issues with versions.

**Comment by romesco** [comment]
Thanks for the quick responses! The manual linking fixed this issue! Is this something that is determined by the CMakeLists mamba uses when installing `ros-melodic-ros-core`? I guess these are pulled down from the robostack channel?

**Comment by wolfv** [comment]
Hi @romesco thanks for filing this bug report. We have rebuilt the packages and this should work now. Would you mind givign it another shot?

**Comment by martimorta** [comment]
Hi,
I was just testin jupyterlab-ros in Binder from [this blog post](https://blog.jupyter.org/jupyterlab-ros-3dc9dab7f421) and launching panda_demo.launch gives this error "while loading shared libraries: liblog4cxx.so.10":

```
process[robot_state_publisher-4]: started with pid [416]
/srv/conda/envs/notebook/lib/robot_state_publisher/robot_state_publisher: error while loading shared libraries: liblog4cxx.so.10: cannot open shared object file: No such file or directory
/srv/conda/envs/notebook/lib/moveit_ros_move_group/move_group: error while loading shared libraries: liblog4cxx.so.10: cannot open shared object file: No such file or directory
failed to start local process: /srv/conda/envs/notebook/lib/moveit_ros_move_group/move_group --debug /joint_states:=/joint_states_desired __name:=move_group __log:=/home/jovyan/.ros/log/09225f88-b0b8-11eb-ad78-9a5db24b6764/move_group-5.log
local launch of moveit_ros_move_group/move_group failed
[robot_state_publisher-4] process has died [pid 416, exit code 127, cmd /srv/conda/envs/notebook/lib/robot_state_publisher/robot_state_publisher __name:=robot_state_publisher __log:=/home/jovyan/.ros/log/09225f88-b0b8-11eb-ad78-9a5db24b6764/robot_state_publisher-4.log].
log file: /home/jovyan/.ros/log/09225f88-b0b8-11eb-ad78-9a5db24b6764/robot_state_publisher-4*.log
[move_group-5] process has died [pid -1, exit code 127, cmd /srv/conda/envs/notebook/lib/moveit_ros_move_group/move_group --debug /joint_states:=/joint_states_desired __name:=move_group __log:=/home/jovyan/.ros/log/09225f88-b0b8-11eb-ad78-9a5db24b6764/move_group-5.log].
log file: /home/jovyan/.ros/log/09225f88-b0b8-11eb-ad78-9a5db24b6764/move_group-5*.log
[robot_state_publisher-4] restarting process
```
I tried again but then it was taking ages to load.
Cheers.
Martí
